name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'symfony/5/*'

jobs:
  build-push-symfony-5:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push symfony 5
        uses: docker/build-push-action@v2
        with:
          file: ./symfony/5/Dockerfile
          context: ./symfony/5/
          push: true
          tags: diazdavid/dev-symfony-5:latest
