name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'php-fpm/5.3/*'

jobs:
  build-push-php-fpm-53:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push php-fpm 5.3
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/5.3/Dockerfile
          context: ./php-fpm/5.3/
          push: true
          tags: diazdavid/dev-php-fpm:5.3