name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-push-php-fpm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push php-fpm 5.3
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/5.3/Dockerfile
          context: ./php-fpm/5.3/
          push: true
          tags: diazdavid/dev-php-fpm:5.3

      - name: Build and push php-fpm 5.6.40
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/5.6.40/Dockerfile
          context: ./php-fpm/5.6.40/
          push: true
          tags: diazdavid/dev-php-fpm:5.6.40

      - name: Build and push php-fpm 7.4.6
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.6/Dockerfile
          context: ./php-fpm/7.4.6/
          push: true
          tags: diazdavid/dev-php-fpm:7.4.6

      - name: Build and push php-fpm 7.4.7
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.7/Dockerfile
          context: ./php-fpm/7.4.7/
          push: true
          tags: diazdavid/dev-php-fpm:7.4.7

      - name: Build and push php-fpm 7.4.10
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.10/Dockerfile
          context: ./php-fpm/7.4.10/
          push: true
          tags: diazdavid/dev-php-fpm:7.4.10

      - name: Build and push php-fpm 8.0.0-beta1
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/8.0.0-beta1/Dockerfile
          context: ./php-fpm/8.0.0-beta1/
          push: true
          tags: diazdavid/dev-php-fpm:8.0.0-beta1

  build-push-php-fpm-opcache:
    needs: build-push-php-fpm

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push php-fpm-opcache 7.4.7
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm-opcache/7.4.7/Dockerfile
          context: ./php-fpm-opcache/7.4.7/
          push: true
          tags: diazdavid/dev-php-fpm:7.4.7-opcache

      - name: Build and push php-fpm-opcache 7.4.10
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm-opcache/7.4.10/Dockerfile
          context: ./php-fpm-opcache/7.4.10/
          push: true
          tags: diazdavid/dev-php-fpm:7.4.10-opcache
