name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'network-tools/*'

jobs:
  build-push-network-tools:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push network-tools
        uses: docker/build-push-action@v6
        with:
          file: ./network-tools/Dockerfile
          context: ./network-tools/
          push: true
          tags: diazdavid/network-tools:latest
          platforms: linux/amd64,linux/arm64
