name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'node/12.17/*'

jobs:
  build-push-node-1217:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push node 12.17
        uses: docker/build-push-action@v2
        with:
          file: ./node/12.17/Dockerfile
          context: ./node/12.17/
          push: true
          tags: diazdavid/dev-node:12.17