name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'high-load-express/*'

jobs:
  build-push-high-load-express:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push high load express
        uses: docker/build-push-action@v2
        with:
          file: ./high-load-express/Dockerfile
          context: ./high-load-express/
          push: true
          tags: diazdavid/high-load-express:latest
